#!/usr/bin/env python3
import sys,re
from datetime import datetime

genders={}

def addGender(word,g):
    if word in genders:
        if g==genders[word]:
            print("duplicate gender entry:%s:%s"%(word,g))
        else:
            print("%s: gender conflict for  %s was %s : "%(g,word,genders[word]))
        return
    genders[word]=g

def showGenders():
    print(datetime.now().strftime("%%  Generated by addGender.py : %Y-%m-%d %H:%M"))    
    for (word,g) in sorted(genders.items()):
        print("gender('%s',\"%s\")."%(word,g))


for line in open(sys.path[0]+"/../lexical-data/englishGenderWords.txt",encoding="utf-8"):
    if line[0]=="#" or len(line)==1:continue
    mots=line.rstrip().split("\t")
    addGender(mots[0].strip(),"m")
    if len(mots)==2:
        addGender(mots[1].strip(),"f")

for role91name in ["have-org-role-91-roles-v1.06.txt","have-rel-role-91-roles-v1.06.txt"]:
    filePath=sys.path[0]+"/../lexical-data/"+role91name
    for line in open(filePath,encoding="utf-8"):
        if line[0]=="#" or len(line)==1 or ":standard" in line:continue
        m = re.match(r'^.+91-ARG2 ([-\w]+)',line)
        word=m.group(1)
        # print("line:%s:%s"%(line.strip(),word))
        g = "f" if re.search("woman|daugther|sister|mother", word) else "m"
        addGender(word,g)
        
showGenders()
